export const tips = {
  tips1:
    'Câu khái niệm "Phương tiện giao thông cơ giới đường bộ" chọn "Kể cả xe máy điện".\n\nCâu khái niệm "Phương tiện giao thông thô sơ đường độ" chọn "Kể cả xe đạp máy".\n\nCâu khái niệm "Người điều khiển giao thông" là "Cành sát giao thông".\n\nCâu khái niệm "Phần đường xe chạy" chọn câu không có chữ "An toàn giao thông".\n\nCâu khái niệm "Làn đường" chọn câu có chữ "An toàn giao thông".\n\nCác câu "Đồ xe: không có giới hạn về thời gian và Dừng xe có giới hạn thời gian" chọn câu số 2.\n\nVề nồng độ cồn, trong máu = 50, trong khí thờ = 0, 25 hoặc không có gì cả trong máu và khí thờ.\nDừng xe, đỗ xe cách lề đường, hè phố không quá 0,25 mét.\n\nGiữ khoảng cách 5 mét với đường sắt.\n\nSử dụng giấy phép lái xe giả cấm 05 năm.\n\nChọn "Cơ quan quản lý giao thông" đối với các trường hợp Xe quá tài, xe quá khổ và xe vận chuyển hàng nguy hiểm.\n\nChọn "UBND cấp tỉnh" đối với trường hợp cấm đi, cấm đổ, cấm dừng, đường ngược chiều. Loại giấy tờ mang theo: Giấy phép lái xe phù hợp với loại xe. Độ tuổi lấy bằng theo hạng (mỗi hạng cách nhau 3 tuổi): 16: Xe dưới 50cm3; 18: Hạng A, B; 21: Hạng C; 24: Hạng D, FC; 27: Hạng E.\n\nĐộ tuổi tối đa người lái xe ô tô hạng E: Nam 55 tuổi và nữ 50 tuổi.\n\nKhông lái xe liên tục quá 4 giờ. Gặp câu hỏi về hạng FE thì chọn Câu 1, hạng FC thì chọn Câu 2.\n\nTốc độ giới hạn của xe: Bên ngoài khu dân cư 80km/h < 3,5 tấn, 70km/h > 3,5 tấn.\n\nTốc độ của xe ô tô trên đường cao tốc, bạn lấy tốc độ (lớn nhất) trong câu hỏi rồi trừ cho 30 thì sẽ ra đáp án đúng.',
  tips2:
    'Đối với các câu có biển báo hiệu lệnh được đặt trước ngã ba, ngã tư. Chọn câu 1 nếu câu hỏi 1 dòng, câu 3 nếu câu hỏi có 2 dòng.\n\nBiển báo cấm máy kéo thì không cấm ô tô tài và ngược lại.\n\nBiển báo cấm rẽ trái thì cấm quay đầu và biển cấm quay đầu thì không cấm rẽ trái.',
  tips3:
    'Đối với câu hỏi liên quan đến việc điều khiển của CSGT, CSGT gið tay thẳng lên thì các loại xe phải đứng lại, đưa 1 hoặc 2 tay giang ngang thì xe trước và đằng sau phải đứng lại.\n\nĐường giao nhau có vòng xuyến nhường bên trái, không có vòng xuyến nhường bên phải.\n\nThấy xuất hiện "Công an" thì chọn câu số 3.\n\nXe nào đã vào ngã tư thì xe đó có quyền ưu tiên đi trước cao nhất.\n\nTiếp đó đến các xe ưu tiên. Trong các xe ưu tiên thì xe cứu hoả có ưu tiên xe quân sự, xe công an, xe cứu thương.\n\nTiếp đó nếu cùng là xe ưu tiên hoặc cùng là xe không ưu tiên thì xét đến đường ưu tiên, tức là xe nào nằm trên đường ưu tiên thì có quyền đi trước (Xem biển báo hoặc tín hiệu đèn).\n\nXe nào không vướng xe khác ở bên phải có quyền đi trước Thứ tự ưu tiên tiếp theo: xe rẽ phài –> xe đi thằng –> xe rẽ trái.',
  tips4:
    'Hiện nay, Trong việc thi bằng lái xe máy thì phần thi thực hành chấm điểm tự động bằng chip. Do máy tự động chấm điểm nên việc thi thực hành tỷ lệ trượt nhiều hơn so với trước. Qua quá trình tổ chức thi sát hạch qua rất nhiều học viên đúc kết ra một số mẹo cần chuẩn bị trước để thi đảm bảo đỗ 100%\n\n1.Tập trước vòng số 8 ở nhà. Phần thi thực hành trượt nhiều nhất là ở phần thi vòng số 8. Do đó, việc bạn đã biết đi xe máy thành thạo nhưng chưa tập qua vòng số 8 thì cũng rất dễ bị trượt. Bạn nên tập qua vòng số 8 càng nhiều lần càng tốt. Ít nhất là lúc đi xe vào vòng số 8 không còn cảm thấy loạng choạng.\n\n2.Hôm thi lên sân thi thật sớm. Tại sao chúng tôi lại khuyên bạn như vậy? Bởi vì xe của bạn thì bạn quen với nó, bạn đi rất ngon lành. Nhưng xe của sân thi thì khác nhiều đấy, nếu bạn không đến sớm để làm quen với nó thì cũng rất dễ trượt. Hơn nữa, buổi thi thường sẽ có rất đông người. Nếu bạn đến sớm thì không phải chờ lâu mới được tập xe. Còn nếu đến muộn thì khả năng phài xếp hàng dài dài mới đến lượt mình.\n\n3.Cách đi đề không bị chạm vạch Đi xe vào từ mép ngoài bền trái, bởi vì như thế thì bánh sau mới không bị đè lên vạch. Nếu bạn đi vào từ mép ngoài bên phải thì nhìn bánh trước vào rất ngon lành, nhưng rất tiếc bánh sau sẽ bị đè lên vạch ngay. Tương tự lúc ra khỏi vòng số 8 cũng như vậy. Bạn phải cho xe ra từ mép ngoài bên trái, nếu không bánh sau của xe cũng sẽ đè lên vạch.\n\nLưu ý: Lúc thi thực hành bạn nên đề xe ở số 3 mà đi. Bởi vì số 4 thì có thể sẽ hơi yếu, nhưng số 1,2 thì sẽ bị giật mạnh. Phần đường gồ ghề bạn nên để số 3 đi và nên đi chậm chậm vừa phải nếu không muốn bay luôn cả người và xe ra ngoài.',
};
