const resources = {
  backArrow: require('./resources/backArrow.png'),
  background: require('./resources/background.png'),
  book: require('./resources/book.png'),
  brain: require('./resources/brain.png'),
  carWifi: require('./resources/carWifi.png'),
  checklist: require('./resources/checklist.png'),
  chevronLeft: require('./resources/chevronLeft.png'),
  chevronLeftPurple: require('./resources/chevronLeftPurple.png'),
  chevronRight: require('./resources/chevronRight.png'),
  chevronRightGray: require('./resources/chevronRightGray.png'),
  chevronRightPurple: require('./resources/chevronRightPurple.png'),
  delete: require('./resources/delete.png'),
  directionBoard: require('./resources/directionBoard.png'),
  document: require('./resources/document.png'),
  download: require('./resources/download.png'),
  driver: require('./resources/driver.png'),
  eLearning: require('./resources/eLearning.png'),
  email: require('./resources/email.png'),
  menu: require('./resources/menu.png'),
  menuAnswer: require('./resources/menuAnswer.png'),
  random: require('./resources/random.png'),
  rating: require('./resources/rating.png'),
  rightArrow: require('./resources/rightArrow.png'),
  scale: require('./resources/scale.png'),
  share: require('./resources/share.png'),
  sync: require('./resources/sync.png'),
  talk: require('./resources/talk.png'),
  task: require('./resources/task.png'),
  trafficLights: require('./resources/trafficLights.png'),
  trash: require('./resources/trash.png'),
  vote: require('./resources/vote.png'),
  warning: require('./resources/warning.png'),
};

export default resources;
